### PR TITLE
feat(board): add boards

### PR DESCRIPTION
**Pull request by WikiRik**
Tests are still missing

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
I'll check this once #1 would be merged

**Comment by WikiRik** [comment]
Not sure if I've copied the api-requests test correctly (@serge1peshcoff can you check) and as mentioned above it's still missing tests, but should be enough for @LeonVreling to work further on it.

**Comment by WikiRik** [comment]
Okay, fixed the test. Took me a bit longer than I wanted but in the end I figured it out. @LeonVreling do you feel like making the rest of the tests when you are implementing the other board change features? https://myaegee.atlassian.net/browse/MA-141 has a list of tests that I've thought of already

**Comment by WikiRik** [comment]
@LeonVreling will add more tests and do the rest of the implementation in another PR

**Comment by WikiRik** [comment]
@serge1peshcoff could you take a look at this?

**Comment by WikiRik** [comment]
@LeonVreling don't forget that https://github.com/AEGEE/network/pull/54 needs to be merged in this as well, otherwise some tests might fail

**Comment by WikiRik** [comment]
@LeonVreling how much do you still want to add in this PR? I would like to update CircleCI and Node here as well but I would like to merge this first

**Comment by LeonVreling** [comment]
Some things are broken after the addition of mailer. One thing that needs to be added (and hopefully fixes brokenness) is the input validation

**Review by HassanCehef — APPROVED** [review]

**Pull request merged**
