### PR TITLE
chore(codeql-analysis): add codeql analysis

### PR DESCRIPTION
**Pull request by WikiRik**
This looks fancy, so I want to test it out here

### CODE REVIEW

**Review by serge1peshcoff — APPROVED** [review]
can you post the result of it later somewhere? no idea what does it do, but maybe if that'll work nice we can integrate it into other services

**Comment by WikiRik** [comment]
> can you post the result of it later somewhere? no idea what does it do, but maybe if that'll work nice we can integrate it into other services

Of course!

**Comment by WikiRik** [comment]
@serge1peshcoff https://github.com/AEGEE/network/security/code-scanning

**Comment by linuxbandit** [comment]
looks nice

**Pull request merged**
